const NAMES = [
  "Agent Vibe",
  "Captain Hype",
  "DJ Volt",
  "Master Pulse",
  "Commander Beat",
  "Doctor Flash",
  "Professor Glow",
  "Officer Spark",
  "Chef Flow",
  "Pilot Echo",
  "Coach Loop",
  "Hunter Boom",
  "Rider Pop",
  "Chaser Buzz",
  "Runner Blast",
  "Skipper Snap",
  "Flyer Dash",
  "Ranger Bolt",
  "Chief Jolt",
  "Boss Rush",
  "King Wave",
  "Duke Fuse",
  "Baron Flex",
  "Major Ace",
  "Alpha Jax",
  "Omega Zane",
  "Titan Neon",
  "Hero Nova",
  "Star Cruz",
  "Buddy Blaze",
  "Lucky Rocco",
  "Happy Zack",
  "Sunny Rox",
  "Sonny Maxx",
  "Rocky Fox",
  "Rusty Jet",
  "Dusty Rex",
  "Smokey Riot",
  "Ziggy Rogue",
  "Iggy Storm",
  "Ozzy Spike",
  "Jaxxon Shadow",
  "Zander Ghost",
  "Ryder Matrix",
  "Wilder Pixel",
  "Maverick Laser",
  "Phoenix Sonic",
  "Axel Turbo",
  "Diesel Nitro",
  "Harley Cosmo",
  "Marlo Rocket",
  "Brix Radar",
  "Flint Ranger",
  "Stone Hunter",
  "Steel Rider",
  "Iron Chaser",
  "Brick Flyer",
  "Rock Runner",
  "Maxx Skipper",
  "Zack Captain",
  "Rox Chief",
  "Fox Boss",
  "Jet King",
  "Rex Duke",
  "Riot Baron",
  "Rogue Major",
  "Storm Alpha",
  "Spike Omega",
  "Shadow Titan",
  "Ghost Hero",
  "Matrix Star",
  "Pixel Lucky",
  "Laser Happy",
  "Sonic Sunny",
  "Turbo Buddy",
  "Nitro Sonny",
  "Cosmo Rocky",
  "Rocket Rusty",
  "Radar Dusty",
  "Ranger Smokey",
  "Hunter Ziggy",
  "Rider Iggy",
  "Chaser Ozzy",
  "Flyer Jaxxon",
  "Runner Zander",
  "Skipper Ryder",
  "Captain Wilder",
  "Chief Maverick",
  "Boss Phoenix",
  "King Axel",
  "Duke Diesel",
  "Baron Harley",
  "Major Marlo",
  "Alpha Brix",
  "Omega Flint",
  "Titan Stone",
  "Hero Steel",
  "Star Iron",
  "Lucky Brick"
] as const;

const ROOM_NAMES = [
  "The Vibe Room",
  "The Hub Club",
  "The Zone Spot",
  "The Spot Lounge",
  "The Wave Room",
  "The Hype Zone",
  "The Chill Spot",
  "The Rush Club",
  "The Mix Room",
  "The Fuse Zone",
  "The Volt Club",
  "The Pulse Room",
  "The Beat Box",
  "The Flash Lounge",
  "The Glow Room",
  "The Spark Zone",
  "The Flow Studio",
  "The Echo Lounge",
  "The Loop Room",
  "The Jump Zone",
  "The Boom Room",
  "The Pop Club",
  "The Buzz Lounge",
  "The Blast Zone",
  "The Snap Room",
  "The Base Camp",
  "The Core Room",
  "The Grid Zone",
  "The Peak Club",
  "The Club House",
  "The Crew Lounge",
  "The Gang Spot",
  "The Squad Room",
  "The Link Zone",
  "The Sync Club",
  "The Hideout",
  "The Secret Spot",
  "The Underground",
  "The Club House",
  "The Safe House",
  "The Base Camp",
  "The Corner Room",
  "The Backyard",
  "The Top Floor",
  "The Green Room",
  "The Red Room",
  "The Blue Room",
  "The Dark Room",
  "The Sound Box",
  "The Music Box",
  "The Party Box",
  "The Boom Box",
  "The Glass House",
  "The Brick Room",
  "The Neon Den",
  "The Chill Den",
  "The Game Room",
  "The VIP Room",
  "The Main Stage",
  "The Backstage",
  "The Station",
  "The Junction",
  "The Loft",
  "The Attic",
  "The Cave",
  "The Lab",
  "The Studio",
  "The Cabin",
  "The Oasis",
  "The Fort",
  "The Good Vibes Room",
  "The Fun Factory",
  "The Party Starter",
  "The Night Owl",
  "The Midnight Club",
  "The Chill Zone",
  "The Happy Hour",
  "The Non-Stop Club",
  "The High Energy Room",
  "The Dance Zone",
  "The Loud Lounge",
  "The Playlist Room",
  "The Crazy Room",
  "The Super Party",
  "The Live Wire",
  "The Fire Room",
  "The Wild Spot",
  "The Joy Room",
  "The Smile Studio",
  "The Laugh Lab",
  "The Remix Room",
  "The Heavy Bass",
  "The Big Bang",
  "The Weekend Hub",
  "The Sun Downer",
  "The Night Out",
  "The Star Night",
  "The Dream Team Room",
  "The Best Day Ever",
  "The Final Stop"
] as const;

function pick<T>(values: readonly T[]) {
  return values[Math.floor(Math.random() * values.length)];
}

export function generateDisplayName() {
  return pick(NAMES);
}

export function generateRoomName() {
  return pick(ROOM_NAMES);
}
